version: '2'
services:
    edasserverapplication-app:
        image: edasserverapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://edasserverapplication-mysql:3306/edasserverapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    edasserverapplication-mysql:
        extends:
            file: mysql.yml
            service: edasserverapplication-mysql
